var express = require('express')
var server = express()
var route_pages = require('./route/pages')
var route_api = require('./route/api')
server.use(express.json())
server.use(express.urlencoded({ extended: true }))
server.set('views', __dirname + '/views')
server.set('view engine', 'ejs')
server.use('/pages', route_pages)
server.get('/api', route_api)
server.listen(5656)